# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Stephanie Paige Ogburn
email: stephanie.ogburn@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  User Research, UX Writing, Content Strategy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stephanieogburn.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  spogburn

# Build settings
markdown: kramdown
remote_theme: "mmistakes/so-simple-theme@3.2.0"
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/

# Styling
google_fonts:
  - name: "Open Sans Condensed"
    weights: "300,400,400i,700,700i"
  - name: "Raleway"
    weights: "200,400,400i,700,700i"

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
  # Recipe defaults
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: page


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
